# Generated by Django 3.1.7 on 2021-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=10)),
                ('task_description', models.TextField(blank=True, max_length=10, null=True)),
                ('experience_years', models.TimeField()),
                ('complete_choice', models.BooleanField(default=None)),
            ],
        ),
    ]
