# Generated by Django 3.1.7 on 2021-03-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
