# Generated by Django 3.1.7 on 2021-03-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_auto_20210313_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='experience_years',
            new_name='task_time',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=100),
        ),
    ]
